template = "https://github.com/giellalt/template-lang-und"
rev_id = 247
template_sha = "c61ba7e0fbfa7e63d11bcd3461406bb80e54e26a"

[replacements]
__GLOTTOLOG_ID__ = "livv1244"
__REPO__ = "lang-liv"
__UND2C__ = "liv"
__UNDEFINED__ = "Liv"
__UND__ = "liv"
